### ISSUE TITLE
Inequality ToString Improvements

### ISSUE THREAD

**Issue by ghost** [joel-heath/NEAConsole#2]
### More than 3 variables
With less than 3 variables x, y, z is sufficient, but beyond x1, x2, x3 etc should be used.

### Negatives
With a first coefficient of 2 and a second of -4, the current display is
`2x + -4y`
This should be
`2x - 4y`

However the first coefficient or constant term are negative they should remain as they are.

**Comment by joel-heath** [comment]
Fixed as of commit 560823c6969211e7d39683c95580162de51bff68
